# model config
arch: "mae_base"
finetune_type: "none"
ckpt_dir: "./ckpt/"
load_ckpt: true
seq_len: 100
periodicity: 10
image_method: "multi_var"
image_mask: "complementary"
task: "rec"
denormalize: true

# nf config
use_nf: true
n_blocks: 2
n_sensor: 2
input_size: 2
hidden_size: 32
n_hidden: 1
cond_label_size: 0
activation: "tanh"
input_order: "sequential"
batch_norm: false
lambda_nf: 0.2
lambda_rec: 1
nf_mode: "rand"

# data config
data: "tab"
data_path: "./data/tab"
tab_csv_file: "CalIt2.csv"
batch_size: 128
num_workers: 8
data_ratio: 1

# exp config
mode: "nf-train"
exp_name: "tab"
pic_save_path: "./visual_pic/"
epochs: 5
lr: 0.001
anormly_ratio: 0.9

