# model config
arch: "mae_base"
finetune_type: "none"
ckpt_dir: "./ckpt/"
load_ckpt: true
seq_len: 196
periodicity: 1
norm_const: 0.4
image_method: "multi_var"
image_mask: "complementary"
task: "rec"
denormalize: true
use_new_nf: true

# nf config
use_nf: true
n_blocks: 5
n_sensor: 25
input_size: 25
hidden_size: 64
n_hidden: 1
cond_label_size: 0
activation: "tanh"
input_order: "sequential"
batch_norm: false
lambda_nf: 0.01
lambda_rec: 1
nf_mode: "rand"

# data config
data: "psm"
data_path: "./data/PSM"
batch_size: 128
num_workers: 4
data_ratio: 1.0
num_vars: 25

# exp config
mode: nf-train
exp_name: "psm"
pic_save_path: "./visual_pic/"
epochs: 5
lr: 0.001
anormly_ratio: 20
